"""The README that ships beside the output, written by INSPECTING the directory.

Not from a template, and not from what the run intended to write. A README composed from
intentions describes a run that may have failed halfway; one composed from the directory describes
what a reader will actually find. Where the two disagree, the directory is right.

It answers six questions in a fixed order, and the sixth - what is missing, or cannot be done with
this output - is the one most worth writing and the one most often left out. A processed object
whose provenance cannot be reconstructed is not a result, it is a liability.
"""
from __future__ import annotations
from pathlib import Path


def _tree(out):
    lines = []
    for d in ("objects", "tables", "figures", "reports"):
        p = out / d
        if not p.is_dir():
            continue
        fs = sorted(x for x in p.iterdir() if x.is_file())
        if not fs:
            continue
        by = {}
        for f in fs:
            by.setdefault(f.suffix.lower() or "(no suffix)", []).append(f)
        for suf, group in sorted(by.items()):
            size = sum(x.stat().st_size for x in group)
            unit = f"{size / 1e9:.2f} GB" if size > 5e8 else f"{size / 1e6:.1f} MB"
            lines.append(f"| `{d}/*{suf}` | {len(group)} | {unit} | "
                         + (", ".join(f"`{x.name}`" for x in group[:3])
                            + (", …" if len(group) > 3 else "")) + " |")
    for f in sorted(x for x in out.iterdir() if x.is_file()):
        lines.append(f"| `{f.name}` | 1 | {f.stat().st_size / 1e3:.1f} kB | |")
    return "\n".join(lines)


def write_readme(out_dir, payload):
    out = Path(out_dir)
    ch = payload.get("chosen") or {}
    default = ch.get("default")
    ms = payload.get("methods", [])
    embeds = [m["method"] for m in ms if m.get("kind") == "embed"]
    obj = Path(payload.get("object", "")).name or "(no object written)"
    sent = payload.get("sentinels") or {}
    n_sent = sum(sent.values())
    summ = payload.get("summary", {})

    txt = f"""# scIntegrate output

Written by scintegrate {payload.get('version')} on {payload.get('generated')}.
**This file was generated by inspecting this directory**, not from a template, so it describes
what is actually here.

## 1. What is this, and where did it come from?

Integration of **{payload.get('n_cells', 0):,} cells × {payload.get('n_genes', 0):,} genes**,
batched on `{payload.get('batch_key')}`, annotated by `{payload.get('label_key')}`.

- **input**: `{payload.get('input') or payload.get('h5ad', '')}`
- **produced by**: `scintegrate integrate`
- **methods compared**: {', '.join(m['method'] for m in ms) or 'none'}
- **methods NOT compared**: {', '.join(f"{k} ({v})" for k, v in (payload.get('not_compared') or {}).items()) or 'none'}
- **design**: {payload.get('design')}

## 2. What is the layout?

| path | files | size | examples |
|---|---|---|---|
{_tree(out)}

## 3. What does each file contain?

`objects/{obj}` is the deliverable and carries:

| slot | what it holds | scale |
|---|---|---|
| `X` | expression | **log1p of library-size-normalised counts**, normalised over all samples together |
| `layers['counts']` | the same cells and genes | **raw integer counts** — what the count models were trained on |
| `layers['lognorm']` | identical values to `X` | named explicitly so `X`'s scale is never implicit |
| `obsm['X_pca']` | the **uncorrected** baseline | kept permanently, so `none` stays comparable |
{chr(10).join(f"| `obsm['X_{m}']` | the {m} corrected space | latent coordinates |" for m in embeds)}
{chr(10).join(f"| `obsm['X_umap_{m}']` | 2-D view of {m} | for figures only, never for metrics |" for m in embeds)}
| `obsm['X_umap']` | a copy of **{'X_umap_' + default if default else 'nothing — no default was chosen'}** | so a plotting call with no argument uses the chosen one |
| `obs` | `{', '.join([payload.get('batch_key', ''), payload.get('label_key', '')])}` and the declared design factors | nothing else — see question 6 |
| `uns['scintegrate']` | the benchmark, the choice and its reason, the constraint on use | plain types only, so other readers can hold it |

Tables are CSV, one per thing the report shows, openable without this tool.

## 4. What processing has already been applied?

- **k** = {payload.get('k')} for every neighbourhood measurement
- **n_pcs** = {payload.get('n_pcs')}; **n_latent** = {payload.get('n_latent')} for scVI/scANVI
- **seed** = {payload.get('seed')}
- **scIB total** = {payload.get('w_bio')} × biological conservation + {round(1 - float(payload.get('w_bio', 0.6)), 3)} × batch correction
- **no gene class was excluded** from highly-variable selection. Where a mask was present on the
  input it was reused verbatim; a mask is a restriction on what a model SEES and never a route by
  which genes leave the study. Every gene remains in this object.
- **{n_sent:,} cells carry an annotator sentinel** ({', '.join(f'{k} {v:,}' for k, v in sorted(sent.items()))}).
  They are excluded from the label-based metrics ONLY. They are present in every embedding, every
  figure and this object. `tables/label_sentinels_by_arm.csv` gives their distribution per arm of
  the design — read it rather than assuming it is even.

## 5. Which file is the intended input for the next step?

**Use `objects/{obj}`.** It is the only object here.

- Reach for `obsm['X_umap']` or `uns['scintegrate']['default_embedding']`
  ({'`X_' + default + '`' if default else 'not set — no default was chosen'}) for visualisation
  and clustering.
- Reach for `layers['counts']` for anything that models counts, including differential
  expression. No correction here touched it.
- **Do not** use a `X_umap_*` view as an input to a metric or a model. It is two dimensions of a
  nonlinear layout, not the space the correction happened in.

**Read `reports/integration.html` before using the default embedding.** Its *Constraint on use*
section is computed from the design and states what the chosen embedding may and may not carry.

## 6. What is missing, or cannot be done with this output?

- **Nothing here establishes that a batch effect is technical.** The measurements locate structure;
  they cannot say whether removing it was right, because that depends on the next question and
  nothing measured here knows what it is.
- **No label is established as correct.** They are inherited from the annotation, and every limit
  recorded there still applies to every number on this page.
- {'**' + str(len(summ.get('types_below_and_factor_also_unmixed') or [])) + ' cell type(s) are unmixed on the batch key AND on a declared biological factor**: ' + ', '.join(summ.get('types_below_and_factor_also_unmixed') or []) + '. There the two are the same structure and a correction on the batch key removes the biological contrast with it. That is not recoverable from a corrected embedding afterwards.' if (summ.get('types_below_and_factor_also_unmixed')) else 'No cell type was unmixed on both the batch key and a declared factor.'}
- **Metrics that could not be computed are listed** in `tables/scib_absent.csv`, and the number of
  metrics behind each aggregate travels with it in `tables/scib_aggregate.csv`. A total from eight
  metrics is not comparable with a total from nine.
- **`obs` is deliberately narrow.** If a downstream step needs a covariate that is not here, add it
  to the design table and re-run rather than joining it on afterwards — a covariate joined by
  position is a covariate nobody can check.
"""
    p = out / "README.md"
    p.write_text(txt, encoding="utf-8")
    return p
